
WebDKP_Options = {
	["SelectedTableId"] = 1,
	["AutofillEnabled"] = 1,
	["MiniMapButtonAngle"] = 0.4302272732931596,
	["AutofillThreshold"] = 3,
	["AutoAwardEnabled"] = 1,
}
WebDKP_Log = {
	["测试分数 2025-11-10 23:20:21"] = {
		["awarded"] = {
			["安娜希尔"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "安娜希尔",
			},
			["郁眠"] = {
				["class"] = "圣骑士",
				["name"] = "郁眠",
			},
			["认养一头母牛"] = {
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
			["三元奶"] = {
				["class"] = "牧师",
				["name"] = "三元奶",
			},
			["坏小猪哥哥"] = {
				["class"] = "战士",
				["name"] = "坏小猪哥哥",
			},
			["有肉肉"] = {
				["class"] = "猎人",
				["name"] = "有肉肉",
			},
			["泰兰徳羽月"] = {
				["class"] = "猎人",
				["name"] = "泰兰徳羽月",
			},
			["Usotall"] = {
				["class"] = "萨满祭司",
				["name"] = "Usotall",
			},
			["石菖蒲"] = {
				["class"] = "术士",
				["name"] = "石菖蒲",
			},
			["神神气气"] = {
				["class"] = "盗贼",
				["name"] = "神神气气",
			},
			["程灵素"] = {
				["class"] = "牧师",
				["name"] = "程灵素",
			},
			["小黑手佳乐"] = {
				["class"] = "战士",
				["name"] = "小黑手佳乐",
			},
			["可爱的狸狸"] = {
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
			["巨蟹座祭司"] = {
				["class"] = "萨满祭司",
				["name"] = "巨蟹座祭司",
			},
			["葫芦仙"] = {
				["class"] = "牧师",
				["name"] = "葫芦仙",
			},
			["莉莉丝丨"] = {
				["class"] = "德鲁伊",
				["name"] = "莉莉丝丨",
			},
			["阿牛"] = {
				["class"] = "战士",
				["name"] = "阿牛",
			},
			["如月舞"] = {
				["class"] = "圣骑士",
				["name"] = "如月舞",
			},
			["Alexistina"] = {
				["class"] = "战士",
				["name"] = "Alexistina",
			},
			["淬锋"] = {
				["class"] = "战士",
				["name"] = "淬锋",
			},
			["小包子"] = {
				["class"] = "术士",
				["name"] = "小包子",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "测试分数",
		["foritem"] = "false",
		["points"] = 5,
		["date"] = "2025-11-10 23:20:21",
		["tableid"] = 1,
	},
	["test 2025-11-10 22:53:03"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
			["三元奶"] = {
				["class"] = "牧师",
				["name"] = "三元奶",
			},
			["坏小猪哥哥"] = {
				["class"] = "战士",
				["name"] = "坏小猪哥哥",
			},
			["如月舞"] = {
				["class"] = "圣骑士",
				["name"] = "如月舞",
			},
			["石菖蒲"] = {
				["class"] = "术士",
				["name"] = "石菖蒲",
			},
			["神神气气"] = {
				["class"] = "盗贼",
				["name"] = "神神气气",
			},
			["程灵素"] = {
				["class"] = "牧师",
				["name"] = "程灵素",
			},
			["天蓝色的学"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "天蓝色的学",
			},
			["锦果果"] = {
				["class"] = "战士",
				["name"] = "锦果果",
			},
			["我大戈六六"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "我大戈六六",
			},
			["Aviere"] = {
				["class"] = "圣骑士",
				["name"] = "Aviere",
			},
			["还得我来"] = {
				["class"] = "法师",
				["name"] = "还得我来",
			},
			["Alexistina"] = {
				["class"] = "战士",
				["name"] = "Alexistina",
			},
			["大辣条"] = {
				["class"] = "德鲁伊",
				["name"] = "大辣条",
			},
			["皮皮丶"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "皮皮丶",
			},
			["巨蟹座祭司"] = {
				["class"] = "萨满祭司",
				["name"] = "巨蟹座祭司",
			},
			["冰猫"] = {
				["class"] = "战士",
				["name"] = "冰猫",
			},
			["安娜希尔"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "安娜希尔",
			},
			["郁眠"] = {
				["class"] = "圣骑士",
				["name"] = "郁眠",
			},
			["血影寂灭"] = {
				["guild"] = "MirAcLe",
				["class"] = "盗贼",
				["name"] = "血影寂灭",
			},
			["柠檬酸了心"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "柠檬酸了心",
			},
			["老牛爹爹"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "老牛爹爹",
			},
			["嘎哈"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "嘎哈",
			},
			["此情念念不忘"] = {
				["class"] = "术士",
				["name"] = "此情念念不忘",
			},
			["一染尽红尘"] = {
				["class"] = "战士",
				["name"] = "一染尽红尘",
			},
			["泰兰徳羽月"] = {
				["class"] = "猎人",
				["name"] = "泰兰徳羽月",
			},
			["Usotall"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "Usotall",
			},
			["小包子"] = {
				["class"] = "术士",
				["name"] = "小包子",
			},
			["雨爷"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "雨爷",
			},
			["可爱的狸狸"] = {
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
			["小黑手佳乐"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "小黑手佳乐",
			},
			["丨吉丨安娜"] = {
				["class"] = "法师",
				["name"] = "丨吉丨安娜",
			},
			["葫芦仙"] = {
				["class"] = "牧师",
				["name"] = "葫芦仙",
			},
			["莉莉丝丨"] = {
				["class"] = "德鲁伊",
				["name"] = "莉莉丝丨",
			},
			["阿牛"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "阿牛",
			},
			["圣经丶冰"] = {
				["class"] = "圣骑士",
				["name"] = "圣经丶冰",
			},
			["祖鲁希德阿猫"] = {
				["class"] = "法师",
				["name"] = "祖鲁希德阿猫",
			},
			["淬锋"] = {
				["class"] = "战士",
				["name"] = "淬锋",
			},
			["有肉肉"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "有肉肉",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "test",
		["foritem"] = "false",
		["points"] = 1,
		["date"] = "2025-11-10 22:53:03",
		["tableid"] = 1,
	},
	["test 2025-11-10 22:52:30"] = {
		["awarded"] = {
			["安娜希尔"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "安娜希尔",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "test",
		["foritem"] = "false",
		["points"] = 1,
		["date"] = "2025-11-10 22:52:30",
		["tableid"] = 1,
	},
	["下线 2025-10-30 01:10:14"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
		},
		["zone"] = "暴风城",
		["awardedby"] = "安娜希尔",
		["reason"] = "下线",
		["foritem"] = "false",
		["points"] = 1,
		["date"] = "2025-10-30 01:10:14",
		["tableid"] = 1,
	},
	["Version"] = 2,
	["k40boss1 2025-10-30 01:08:02"] = {
		["awarded"] = {
			["安娜希尔"] = {
				["name"] = "安娜希尔",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["认养一头母牛"] = {
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
		},
		["zone"] = "暴风城",
		["date"] = "2025-10-30 01:08:02",
		["reason"] = "k40boss1",
		["foritem"] = "false",
		["points"] = 1,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["上线 2025-10-30 01:10:24"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
		},
		["zone"] = "暴风城",
		["awardedby"] = "安娜希尔",
		["reason"] = "上线",
		["foritem"] = "false",
		["points"] = -1,
		["date"] = "2025-10-30 01:10:24",
		["tableid"] = 1,
	},
	["邪铸纳斯雷萨指轮 2025-11-10 23:20:48"] = {
		["awarded"] = {
			["三元奶"] = {
				["class"] = "牧师",
				["name"] = "三元奶",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "邪铸纳斯雷萨指轮",
		["foritem"] = "true",
		["points"] = -3,
		["date"] = "2025-11-10 23:20:48",
		["tableid"] = 1,
	},
	["测试扣分 2025-11-10 23:20:32"] = {
		["awarded"] = {
			["安娜希尔"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "安娜希尔",
			},
			["郁眠"] = {
				["class"] = "圣骑士",
				["name"] = "郁眠",
			},
			["认养一头母牛"] = {
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
			["三元奶"] = {
				["class"] = "牧师",
				["name"] = "三元奶",
			},
			["坏小猪哥哥"] = {
				["class"] = "战士",
				["name"] = "坏小猪哥哥",
			},
			["有肉肉"] = {
				["class"] = "猎人",
				["name"] = "有肉肉",
			},
			["泰兰徳羽月"] = {
				["class"] = "猎人",
				["name"] = "泰兰徳羽月",
			},
			["Usotall"] = {
				["class"] = "萨满祭司",
				["name"] = "Usotall",
			},
			["石菖蒲"] = {
				["class"] = "术士",
				["name"] = "石菖蒲",
			},
			["神神气气"] = {
				["class"] = "盗贼",
				["name"] = "神神气气",
			},
			["程灵素"] = {
				["class"] = "牧师",
				["name"] = "程灵素",
			},
			["小黑手佳乐"] = {
				["class"] = "战士",
				["name"] = "小黑手佳乐",
			},
			["可爱的狸狸"] = {
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
			["巨蟹座祭司"] = {
				["class"] = "萨满祭司",
				["name"] = "巨蟹座祭司",
			},
			["葫芦仙"] = {
				["class"] = "牧师",
				["name"] = "葫芦仙",
			},
			["莉莉丝丨"] = {
				["class"] = "德鲁伊",
				["name"] = "莉莉丝丨",
			},
			["阿牛"] = {
				["class"] = "战士",
				["name"] = "阿牛",
			},
			["如月舞"] = {
				["class"] = "圣骑士",
				["name"] = "如月舞",
			},
			["Alexistina"] = {
				["class"] = "战士",
				["name"] = "Alexistina",
			},
			["淬锋"] = {
				["class"] = "战士",
				["name"] = "淬锋",
			},
			["小包子"] = {
				["class"] = "术士",
				["name"] = "小包子",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "测试扣分",
		["foritem"] = "false",
		["points"] = -3,
		["date"] = "2025-11-10 23:20:32",
		["tableid"] = 1,
	},
	["项链 2025-11-10 22:54:54"] = {
		["awarded"] = {
			["安娜希尔"] = {
				["name"] = "安娜希尔",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "荒芜巨岩",
		["date"] = "2025-11-10 22:54:54",
		["reason"] = "项链",
		["foritem"] = "true",
		["points"] = 2,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
}
WebDKP_DkpTable = {
	["状元猎"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["佛曰我要劫色"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["凉拌冰盖草"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["法海和尚"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["云山乱洋"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["雾中刃"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["太阳当家"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["丁棍儿"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["六十三级精英"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["錢四面八方來"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["叶落丶翼德"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["吃我小火球"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["皮皮丶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "法师",
	},
	["奇犽"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["南溪"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "圣骑士",
		["Selected"] = false,
	},
	["尛尛灬尛戰弑"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["Gty"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["茉莉山泉"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["孙大蟀"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["爱呀燕子"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["丶牛魔"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["丨莞儿丨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["冥心法天运"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["圣经丶冰"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["状元妞"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["夏日傍晚"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["三元奶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["Lightbreeze"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["神神气气"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["制式寒冰箭"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["小黑手佳乐"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "战士",
	},
	["苒苒升起"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["西林"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["北冥宥魚"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["幸运弯钩"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["深藏魔力"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["安娜希尔"] = {
		["dkp1"] = 0,
		["dkp_1"] = 7,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["奥巴黛斯"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["希尔瓦娜丝"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["血影寂灭"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["凶神二萨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["顶多多"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "圣骑士",
		["Selected"] = false,
	},
	["Casdee"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "圣骑士",
		["Selected"] = false,
	},
	["天天开鑫"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["骚骚更健康"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["古今"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["小咤精丶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["Moriartyz"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["锤锤头"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["冬久"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["假死避雷"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["猎杀狂"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["Ikunxsing"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["破晓之矢"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["阿迩忒弥絲丝"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["姬玉"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["林國栋"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["雷德王"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["牧娜丽莎"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["俺去也"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "圣骑士",
		["Selected"] = false,
	},
	["佐佐木希"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["寄风尘"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["酷酷逗"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["悍匪唐三藏"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["低杆卍左塞"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["破心中贼难"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["拉什福德"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["有肉肉"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["疯狂小凤梨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["风水剑"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "术士",
	},
	["静鸡鸡"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["Spoor"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "术士",
	},
	["蜘蛛精四姐"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["卧了个槽"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["妇科大拿"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["超级队友"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["缺大德了"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["乘你病要你命"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["慈世平"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["術大招蜂"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "术士",
	},
	["大厨男"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["青衫醉剑"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["佐佐助"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["你们的大眼妹"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "圣骑士",
		["Selected"] = false,
	},
	["散人有德"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["戈壁王哥"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "术士",
	},
	["一滴滴的滴落"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["程灵素"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["开丶始"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "术士",
	},
	["無间灬萨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "萨满祭司",
		["Selected"] = false,
	},
	["丶微雨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["个子变高了"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "萨满祭司",
		["Selected"] = false,
	},
	["发力有限"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["乔治马"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["巨蟹座祭司"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["雁飞天"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "萨满祭司",
		["Selected"] = false,
	},
	["郁眠"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["慢冷"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["柠檬酸了心"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "法师",
	},
	["嘎哈"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["墨羽辰"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["海无量"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "萨满祭司",
		["Selected"] = false,
	},
	["啊雕雕"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["灭剑在龙渊"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["祖鲁希德阿猫"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "法师",
	},
	["约翰德蒙斯"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "圣骑士",
		["Selected"] = false,
	},
	["星月神话丶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["德心赢手"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["斩乄殺"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["Ssicdmg"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["聖战"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["Ronn"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["奥术学识"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["团长别逼逼嘞"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["盐汁油梨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["心醉"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["大皮牙子"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["橙黄橘子"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["求不得"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["哈哈迪斯"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["君君德小霸王"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["天宝大将"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["一鹿有你"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["大人是爱我的"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["盗义道"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["一染尽红尘"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "战士",
	},
	["泰兰徳羽月"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["Usotall"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["芊与芊结"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["黑刺"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["低调小萨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "萨满祭司",
		["Selected"] = false,
	},
	["阿波罗传奇"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "圣骑士",
		["Selected"] = false,
	},
	["紫薯真好吃"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "术士",
	},
	["三天半年闲"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["紫漠天辰丶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "萨满祭司",
		["Selected"] = false,
	},
	["Reichenbach"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["瑟兰杜伊"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["黑椒牛筋煲"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["咖丶啡"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "术士",
		["Selected"] = false,
	},
	["阿释密达丶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "术士",
		["Selected"] = false,
	},
	["坏小猪哥哥"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "战士",
	},
	["宝藏白月光"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["清水萝卜头"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["石菖蒲"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "术士",
	},
	["夜木小德"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["深渊步行者"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["天蓝色的学"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["class"] = "战士",
		["Selected"] = false,
	},
	["希女王闺蜜"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["Magez"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["百般丶挑剔"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["Aviere"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["Vancelin"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["从头再试"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["Twila"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["杰德丶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["风流德有邻"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["女侠饶命"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["小软泥怪"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["老牛爹爹"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["无尽信仰"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["东风路走九遍"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["可爱的狸狸"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["熊猫金虎"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["弄我萨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["请恕我拦轿"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["不爱吃鱼"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["爱烧饼"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "圣骑士",
		["Selected"] = false,
	},
	["福尔摩斯丶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "术士",
	},
	["未知目标"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
	},
	["猫咪归来"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["甘叨夫"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["咕德喵柠"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["鹤羽剑"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["无敌牛虱"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["幽冥德"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["影玉"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["阿牛"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "战士",
	},
	["春风足道"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["鲷猊弓龟"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["可爱的孟鹤堂"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["大辣条"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["突然"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "术士",
	},
	["锦果果"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "战士",
	},
	["公羊道格"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "术士",
		["Selected"] = false,
	},
	["雨爷"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["Srgdrsef"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["禹希"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["满怒牛"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["山川不朽"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["神谕者"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["椒丝腐乳西瓜"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["躺赢冠军"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["大海盗"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["金发阿幺"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["咖啡灬"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["脆皮辣子"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["奶八方"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["扯不完的蛋"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["瑶风"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["阿庆"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["慈悲喜舍"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["看我猪蹄"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["还得我来"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "法师",
	},
	["淬锋"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "战士",
	},
	["随机缘分"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["此情念念不忘"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "术士",
	},
	["锈栓"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "术士",
		["Selected"] = false,
	},
	["Honhjie"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["Arcis"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["伴盏流年"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["雾眠"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["黑海岸路霸"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["死神镰刀"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["Brr"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["煮酒论英雄"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["依稀有梦"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["禾光"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["白相相"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["波兰小诗"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "圣骑士",
		["Selected"] = false,
	},
	["塞纳硫斯之路"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["德顿先生"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["丨吉丨安娜"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "法师",
	},
	["华茂春松"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["林丶阿加雷斯"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["石头贼"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["秋刀奈"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["夏树茂木"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["流氓不可怕"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "术士",
		["Selected"] = false,
	},
	["术灵萱"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "术士",
		["Selected"] = false,
	},
	["Alexistina"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "战士",
	},
	["雪消冰释"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["厚李蝎特丶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["如月舞"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["认养一头母牛"] = {
		["dkp1"] = 0,
		["dkp_1"] = 4,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["Dfdnm"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["占三川"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["我家有枭德"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["來杯二鍋頭"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["丫丫牙牙"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["天渊鬼手"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["冷月乩愁思"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["莉莉丝丨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["你的万水千山"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["德里个德"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["Rovina"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["夜语星空"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["绊你一跟头"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["冰猫"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "战士",
	},
	["怖享涨瘩"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["我大戈六六"] = {
		["dkp1"] = 0,
		["dkp_1"] = 1,
		["Selected"] = false,
		["class"] = "战士",
	},
	["香烟烧灵魂"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["脚踏实地"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["光棍夜的雨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["大水牛"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["老爺们战"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["霜华"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["决定"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["十年磨剑"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["天山法"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["葫芦仙"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["拉布警长"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["寒江孤影"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "圣骑士",
		["Selected"] = false,
	},
	["丶阿卡丽莎"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["半夜嘿呦嘿"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["花狩丶舞"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["守望菜田"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "战士",
		["Selected"] = false,
	},
	["丨乌鸦丨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["卖血上网"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["奔跑面包"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["同塵咊光"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "萨满祭司",
		["Selected"] = false,
	},
	["鳞妖妖"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["小三十三"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["魔九"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["帮我叫个外卖"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["红手春力奶霸"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["小包子"] = {
		["dkp1"] = 0,
		["dkp_1"] = 3,
		["Selected"] = false,
		["class"] = "术士",
	},
	["陆地针灸师"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["厉害的瓜瓜"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "牧师",
		["Selected"] = false,
	},
	["封心贼"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["左卿"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["和平逝者"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["花落缥缈"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "德鲁伊",
		["Selected"] = false,
	},
	["刺挠"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["桑宁"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["秋夜鱼腩"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "法师",
		["Selected"] = false,
	},
	["椒盐芝士"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["雷暴元素"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "萨满祭司",
		["Selected"] = false,
	},
	["招財猫"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["暑假作业"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["欲去还留"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "盗贼",
		["Selected"] = false,
	},
	["瓦丶萨鲁法尔"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["Luckyy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["class"] = "猎人",
		["Selected"] = false,
	},
	["逸然小输"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
}
WebDKP_Tables = {
}
WebDKP_Loot = nil
WebDKP_WebOptions = {
	["ZeroSumEnabled"] = 0,
}
