
WebDKP_Options = {
	["SelectedTableId"] = 1,
	["AutofillEnabled"] = 1,
	["MiniMapButtonAngle"] = 0.4302272732931596,
	["AutofillThreshold"] = 3,
	["AutoAwardEnabled"] = 1,
}
WebDKP_Log = {
	["幻影支配护肩 2025-11-17 21:47:46"] = {
		["awarded"] = {
			["泰兰徳羽月"] = {
				["name"] = "泰兰徳羽月",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "荒芜巨岩",
		["date"] = "2025-11-17 21:47:46",
		["reason"] = "幻影支配护肩",
		["foritem"] = "false",
		["points"] = -25,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["驱错目标 2025-11-17 22:59:25"] = {
		["awarded"] = {
			["可爱的狸狸"] = {
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
		},
		["zone"] = "逆风小径",
		["awardedby"] = "安娜希尔",
		["reason"] = "驱错目标",
		["foritem"] = "false",
		["points"] = -1,
		["date"] = "2025-11-17 22:59:25",
		["tableid"] = 1,
	},
	["集合分 2025-11-17 19:31:03"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
			["三元奶"] = {
				["name"] = "三元奶",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
			["坏小猪哥哥"] = {
				["name"] = "坏小猪哥哥",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["莉莉丝丨"] = {
				["name"] = "莉莉丝丨",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["石菖蒲"] = {
				["name"] = "石菖蒲",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["神神气气"] = {
				["name"] = "神神气气",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["程灵素"] = {
				["name"] = "程灵素",
				["class"] = "牧师",
				["guild"] = "爱游戏爱生活",
			},
			["小黑手佳乐"] = {
				["name"] = "小黑手佳乐",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["锦果果"] = {
				["name"] = "锦果果",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["我大戈六六"] = {
				["name"] = "我大戈六六",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["Aviere"] = {
				["name"] = "Aviere",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["Alexistina"] = {
				["name"] = "Alexistina",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["大辣条"] = {
				["name"] = "大辣条",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["皮皮丶"] = {
				["class"] = "法师",
				["name"] = "皮皮丶",
			},
			["淬锋"] = {
				["name"] = "淬锋",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["安娜希尔"] = {
				["name"] = "安娜希尔",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["郁眠"] = {
				["name"] = "郁眠",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["血影寂灭"] = {
				["name"] = "血影寂灭",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["柠檬酸了心"] = {
				["class"] = "法师",
				["name"] = "柠檬酸了心",
			},
			["老牛爹爹"] = {
				["name"] = "老牛爹爹",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["嘎哈"] = {
				["name"] = "嘎哈",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["大人是爱我的"] = {
				["name"] = "大人是爱我的",
				["class"] = "战士",
				["guild"] = "橘猫在桂花树下而这里是我的平行世界",
			},
			["此情念念不忘"] = {
				["name"] = "此情念念不忘",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["可爱的狸狸"] = {
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
			["泰兰徳羽月"] = {
				["name"] = "泰兰徳羽月",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["Usotall"] = {
				["name"] = "Usotall",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["小包子"] = {
				["name"] = "小包子",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["贼酷之名"] = {
				["name"] = "贼酷之名",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["巨蟹座祭司"] = {
				["name"] = "巨蟹座祭司",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["缺大德了"] = {
				["name"] = "缺大德了",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["一染尽红尘"] = {
				["class"] = "战士",
				["name"] = "一染尽红尘",
			},
			["福尔摩斯丶"] = {
				["class"] = "术士",
				["name"] = "福尔摩斯丶",
			},
			["丨吉丨安娜"] = {
				["name"] = "丨吉丨安娜",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["葫芦仙"] = {
				["name"] = "葫芦仙",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
			["如月舞"] = {
				["name"] = "如月舞",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["雨爷"] = {
				["name"] = "雨爷",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["圣经丶冰"] = {
				["name"] = "圣经丶冰",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["祖鲁希德阿猫"] = {
				["name"] = "祖鲁希德阿猫",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["有肉肉"] = {
				["name"] = "有肉肉",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["约翰德蒙斯"] = {
				["name"] = "约翰德蒙斯",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 19:31:03",
		["reason"] = "集合分",
		["foritem"] = "false",
		["points"] = 2,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["短暂吊坠 2025-11-17 22:08:22"] = {
		["awarded"] = {
			["葫芦仙"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "葫芦仙",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "短暂吊坠",
		["foritem"] = "false",
		["points"] = -55,
		["date"] = "2025-11-17 22:08:22",
		["tableid"] = 1,
	},
	["镣铐 2025-11-17 23:37:48"] = {
		["awarded"] = {
			["淬锋"] = {
				["name"] = "淬锋",
				["class"] = "战士",
				["guild"] = "Unknown",
			},
		},
		["zone"] = "荒芜巨岩",
		["date"] = "2025-11-17 23:37:48",
		["reason"] = "镣铐",
		["foritem"] = "false",
		["points"] = -5,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["虚灵支配之靴 2025-11-17 21:22:10"] = {
		["awarded"] = {
			["血影寂灭"] = {
				["name"] = "血影寂灭",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 21:22:10",
		["reason"] = "虚灵支配之靴",
		["foritem"] = "false",
		["points"] = -17,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["魔网观察者因塔苟斯 2025-11-17 20:05:54"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
			["三元奶"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "三元奶",
			},
			["坏小猪哥哥"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "坏小猪哥哥",
			},
			["莉莉丝丨"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "莉莉丝丨",
			},
			["石菖蒲"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "石菖蒲",
			},
			["神神气气"] = {
				["guild"] = "MirAcLe",
				["class"] = "盗贼",
				["name"] = "神神气气",
			},
			["程灵素"] = {
				["guild"] = "爱游戏爱生活",
				["class"] = "牧师",
				["name"] = "程灵素",
			},
			["天蓝色的学"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "天蓝色的学",
			},
			["锦果果"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "锦果果",
			},
			["我大戈六六"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "我大戈六六",
			},
			["Aviere"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "Aviere",
			},
			["Alexistina"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "Alexistina",
			},
			["大辣条"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "大辣条",
			},
			["皮皮丶"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "皮皮丶",
			},
			["淬锋"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "淬锋",
			},
			["安娜希尔"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "安娜希尔",
			},
			["郁眠"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "郁眠",
			},
			["血影寂灭"] = {
				["guild"] = "MirAcLe",
				["class"] = "盗贼",
				["name"] = "血影寂灭",
			},
			["柠檬酸了心"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "柠檬酸了心",
			},
			["老牛爹爹"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "老牛爹爹",
			},
			["嘎哈"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "嘎哈",
			},
			["大人是爱我的"] = {
				["guild"] = "橘猫在桂花树下而这里是我的平行世界",
				["class"] = "战士",
				["name"] = "大人是爱我的",
			},
			["此情念念不忘"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "此情念念不忘",
			},
			["可爱的狸狸"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
			["泰兰徳羽月"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "泰兰徳羽月",
			},
			["Usotall"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "Usotall",
			},
			["小包子"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "小包子",
			},
			["贼酷之名"] = {
				["guild"] = "MirAcLe",
				["class"] = "盗贼",
				["name"] = "贼酷之名",
			},
			["巨蟹座祭司"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "巨蟹座祭司",
			},
			["缺大德了"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "缺大德了",
			},
			["有肉肉"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "有肉肉",
			},
			["葫芦仙"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "葫芦仙",
			},
			["丨吉丨安娜"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "丨吉丨安娜",
			},
			["福尔摩斯丶"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "福尔摩斯丶",
			},
			["如月舞"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "如月舞",
			},
			["雨爷"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "雨爷",
			},
			["圣经丶冰"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "圣经丶冰",
			},
			["祖鲁希德阿猫"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "祖鲁希德阿猫",
			},
			["小黑手佳乐"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "小黑手佳乐",
			},
			["约翰德蒙斯"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "约翰德蒙斯",
			},
		},
		["zone"] = "卡拉赞之塔",
		["awardedby"] = "安娜希尔",
		["reason"] = "魔网观察者因塔苟斯",
		["foritem"] = "false",
		["points"] = 1,
		["date"] = "2025-11-17 20:05:54",
		["tableid"] = 1,
	},
	["流星披肩 2025-11-17 22:09:28"] = {
		["awarded"] = {
			["老牛爹爹"] = {
				["class"] = "萨满祭司",
				["name"] = "老牛爹爹",
			},
			["葫芦仙"] = {
				["class"] = "牧师",
				["name"] = "葫芦仙",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "流星披肩",
		["foritem"] = "false",
		["points"] = -5,
		["date"] = "2025-11-17 22:09:28",
		["tableid"] = 1,
	},
	["渡鸦守护者的疯狂拥抱 2025-11-17 19:54:48"] = {
		["awarded"] = {
			["神神气气"] = {
				["name"] = "神神气气",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 19:54:48",
		["reason"] = "渡鸦守护者的疯狂拥抱",
		["foritem"] = "false",
		["points"] = -1,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["鲁普图兰 2025-11-17 22:07:51"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
			["三元奶"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "三元奶",
			},
			["坏小猪哥哥"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "坏小猪哥哥",
			},
			["莉莉丝丨"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "莉莉丝丨",
			},
			["石菖蒲"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "石菖蒲",
			},
			["神神气气"] = {
				["guild"] = "MirAcLe",
				["class"] = "盗贼",
				["name"] = "神神气气",
			},
			["程灵素"] = {
				["guild"] = "爱游戏爱生活",
				["class"] = "牧师",
				["name"] = "程灵素",
			},
			["天蓝色的学"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "天蓝色的学",
			},
			["锦果果"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "锦果果",
			},
			["我大戈六六"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "我大戈六六",
			},
			["Aviere"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "Aviere",
			},
			["还得我来"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "还得我来",
			},
			["Alexistina"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "Alexistina",
			},
			["大辣条"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "大辣条",
			},
			["皮皮丶"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "皮皮丶",
			},
			["淬锋"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "淬锋",
			},
			["安娜希尔"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "安娜希尔",
			},
			["郁眠"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "郁眠",
			},
			["血影寂灭"] = {
				["guild"] = "MirAcLe",
				["class"] = "盗贼",
				["name"] = "血影寂灭",
			},
			["柠檬酸了心"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "柠檬酸了心",
			},
			["老牛爹爹"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "老牛爹爹",
			},
			["嘎哈"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "嘎哈",
			},
			["大人是爱我的"] = {
				["guild"] = "橘猫在桂花树下而这里是我的平行世界",
				["class"] = "战士",
				["name"] = "大人是爱我的",
			},
			["此情念念不忘"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "此情念念不忘",
			},
			["可爱的狸狸"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
			["泰兰徳羽月"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "泰兰徳羽月",
			},
			["Usotall"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "Usotall",
			},
			["小包子"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "小包子",
			},
			["巨蟹座祭司"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "巨蟹座祭司",
			},
			["缺大德了"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "缺大德了",
			},
			["小黑手佳乐"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "小黑手佳乐",
			},
			["雨爷"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "雨爷",
			},
			["丨吉丨安娜"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "丨吉丨安娜",
			},
			["葫芦仙"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "葫芦仙",
			},
			["如月舞"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "如月舞",
			},
			["阿牛"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "阿牛",
			},
			["圣经丶冰"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "圣经丶冰",
			},
			["祖鲁希德阿猫"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "祖鲁希德阿猫",
			},
			["有肉肉"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "有肉肉",
			},
			["约翰德蒙斯"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "约翰德蒙斯",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "鲁普图兰",
		["foritem"] = "false",
		["points"] = 1,
		["date"] = "2025-11-17 22:07:51",
		["tableid"] = 1,
	},
	["宽恕罪责吊坠 2025-11-17 20:57:42"] = {
		["awarded"] = {
			["程灵素"] = {
				["guild"] = "爱游戏爱生活",
				["class"] = "牧师",
				["name"] = "程灵素",
			},
		},
		["zone"] = "卡拉赞之塔",
		["awardedby"] = "安娜希尔",
		["reason"] = "宽恕罪责吊坠",
		["foritem"] = "false",
		["points"] = -6,
		["date"] = "2025-11-17 20:57:42",
		["tableid"] = 1,
	},
	["守护者纳尔穆恩 2025-11-17 19:54:11"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["name"] = "认养一头母牛",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["三元奶"] = {
				["name"] = "三元奶",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
			["坏小猪哥哥"] = {
				["name"] = "坏小猪哥哥",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["莉莉丝丨"] = {
				["name"] = "莉莉丝丨",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["石菖蒲"] = {
				["name"] = "石菖蒲",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["神神气气"] = {
				["name"] = "神神气气",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["程灵素"] = {
				["name"] = "程灵素",
				["class"] = "牧师",
				["guild"] = "爱游戏爱生活",
			},
			["小黑手佳乐"] = {
				["name"] = "小黑手佳乐",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["锦果果"] = {
				["name"] = "锦果果",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["我大戈六六"] = {
				["name"] = "我大戈六六",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["Aviere"] = {
				["name"] = "Aviere",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["Alexistina"] = {
				["name"] = "Alexistina",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["大辣条"] = {
				["name"] = "大辣条",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["皮皮丶"] = {
				["name"] = "皮皮丶",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["淬锋"] = {
				["name"] = "淬锋",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["安娜希尔"] = {
				["name"] = "安娜希尔",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["郁眠"] = {
				["name"] = "郁眠",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["血影寂灭"] = {
				["name"] = "血影寂灭",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["柠檬酸了心"] = {
				["name"] = "柠檬酸了心",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["老牛爹爹"] = {
				["name"] = "老牛爹爹",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["嘎哈"] = {
				["name"] = "嘎哈",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["大人是爱我的"] = {
				["name"] = "大人是爱我的",
				["class"] = "战士",
				["guild"] = "橘猫在桂花树下而这里是我的平行世界",
			},
			["此情念念不忘"] = {
				["name"] = "此情念念不忘",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["有肉肉"] = {
				["name"] = "有肉肉",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["泰兰徳羽月"] = {
				["name"] = "泰兰徳羽月",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["Usotall"] = {
				["name"] = "Usotall",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["小包子"] = {
				["name"] = "小包子",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["贼酷之名"] = {
				["name"] = "贼酷之名",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["巨蟹座祭司"] = {
				["name"] = "巨蟹座祭司",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["缺大德了"] = {
				["name"] = "缺大德了",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["天蓝色的学"] = {
				["name"] = "天蓝色的学",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["福尔摩斯丶"] = {
				["name"] = "福尔摩斯丶",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["丨吉丨安娜"] = {
				["name"] = "丨吉丨安娜",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["葫芦仙"] = {
				["name"] = "葫芦仙",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
			["如月舞"] = {
				["name"] = "如月舞",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["雨爷"] = {
				["name"] = "雨爷",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["圣经丶冰"] = {
				["name"] = "圣经丶冰",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["祖鲁希德阿猫"] = {
				["name"] = "祖鲁希德阿猫",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["可爱的狸狸"] = {
				["name"] = "可爱的狸狸",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["约翰德蒙斯"] = {
				["name"] = "约翰德蒙斯",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 19:54:11",
		["reason"] = "守护者纳尔穆恩",
		["foritem"] = "false",
		["points"] = 1,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["格雷迈恩皇家印章 2025-11-17 21:21:25"] = {
		["awarded"] = {
			["石菖蒲"] = {
				["name"] = "石菖蒲",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 21:21:25",
		["reason"] = "格雷迈恩皇家印章",
		["foritem"] = "false",
		["points"] = -2,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["坚定防御之杖 2025-11-17 20:39:39"] = {
		["awarded"] = {
			["大辣条"] = {
				["name"] = "大辣条",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 20:39:39",
		["reason"] = "坚定防御之杖",
		["foritem"] = "false",
		["points"] = -1,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["意外开怪 2025-11-17 21:54:44"] = {
		["awarded"] = {
			["三元奶"] = {
				["name"] = "三元奶",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "逆风小径",
		["date"] = "2025-11-17 21:54:44",
		["reason"] = "幻意外开怪",
		["foritem"] = "false",
		["points"] = -2,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["野蛮支配护腿 2025-11-17 22:35:31"] = {
		["awarded"] = {
			["巨蟹座祭司"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "巨蟹座祭司",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "野蛮支配护腿",
		["foritem"] = "false",
		["points"] = -30,
		["date"] = "2025-11-17 22:35:31",
		["tableid"] = 1,
	},
	["库米沙的破旧斗篷 2025-11-17 21:46:57"] = {
		["awarded"] = {
			["缺大德了"] = {
				["name"] = "缺大德了",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "荒芜巨岩",
		["date"] = "2025-11-17 21:46:57",
		["reason"] = "库米沙的破旧斗篷",
		["foritem"] = "false",
		["points"] = -15,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["国王黑水愤怒下跪 2025-11-17 23:44:14"] = {
		["awarded"] = {
			["天蓝色的学"] = {
				["guild"] = "Unknown",
				["class"] = "战士",
				["name"] = "天蓝色的学",
			},
			["柠檬酸了心"] = {
				["class"] = "法师",
				["name"] = "柠檬酸了心",
			},
			["嘎哈"] = {
				["class"] = "萨满祭司",
				["name"] = "嘎哈",
			},
			["Aviere"] = {
				["class"] = "圣骑士",
				["name"] = "Aviere",
			},
			["还得我来"] = {
				["class"] = "法师",
				["name"] = "还得我来",
			},
			["可爱的狸狸"] = {
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
			["泰兰徳羽月"] = {
				["class"] = "猎人",
				["name"] = "泰兰徳羽月",
			},
			["圣经丶冰"] = {
				["class"] = "圣骑士",
				["name"] = "圣经丶冰",
			},
			["皮皮丶"] = {
				["class"] = "法师",
				["name"] = "皮皮丶",
			},
			["如月舞"] = {
				["class"] = "圣骑士",
				["name"] = "如月舞",
			},
			["约翰德蒙斯"] = {
				["class"] = "圣骑士",
				["name"] = "约翰德蒙斯",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "国王黑水愤怒下跪",
		["foritem"] = "false",
		["points"] = -1,
		["date"] = "2025-11-17 23:44:14",
		["tableid"] = 1,
	},
	["幻影征服护肩 2025-11-17 21:47:20"] = {
		["awarded"] = {
			["小黑手佳乐"] = {
				["name"] = "小黑手佳乐",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "荒芜巨岩",
		["date"] = "2025-11-17 21:47:20",
		["reason"] = "幻影征服护肩",
		["foritem"] = "false",
		["points"] = -19,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["镣铐 2025-11-17 23:08:50"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "镣铐",
		["foritem"] = "false",
		["points"] = -5,
		["date"] = "2025-11-17 23:08:50",
		["tableid"] = 1,
	},
	["国王议会 2025-11-17 21:20:28"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["name"] = "认养一头母牛",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["三元奶"] = {
				["name"] = "三元奶",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
			["坏小猪哥哥"] = {
				["name"] = "坏小猪哥哥",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["莉莉丝丨"] = {
				["name"] = "莉莉丝丨",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["石菖蒲"] = {
				["name"] = "石菖蒲",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["神神气气"] = {
				["name"] = "神神气气",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["程灵素"] = {
				["name"] = "程灵素",
				["class"] = "牧师",
				["guild"] = "爱游戏爱生活",
			},
			["小黑手佳乐"] = {
				["name"] = "小黑手佳乐",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["锦果果"] = {
				["name"] = "锦果果",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["我大戈六六"] = {
				["name"] = "我大戈六六",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["Aviere"] = {
				["name"] = "Aviere",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["还得我来"] = {
				["name"] = "还得我来",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["Alexistina"] = {
				["name"] = "Alexistina",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["大辣条"] = {
				["name"] = "大辣条",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["皮皮丶"] = {
				["name"] = "皮皮丶",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["淬锋"] = {
				["name"] = "淬锋",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["安娜希尔"] = {
				["name"] = "安娜希尔",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["郁眠"] = {
				["name"] = "郁眠",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["血影寂灭"] = {
				["name"] = "血影寂灭",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["柠檬酸了心"] = {
				["name"] = "柠檬酸了心",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["老牛爹爹"] = {
				["name"] = "老牛爹爹",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["嘎哈"] = {
				["name"] = "嘎哈",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["大人是爱我的"] = {
				["name"] = "大人是爱我的",
				["class"] = "战士",
				["guild"] = "橘猫在桂花树下而这里是我的平行世界",
			},
			["此情念念不忘"] = {
				["name"] = "此情念念不忘",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["有肉肉"] = {
				["name"] = "有肉肉",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["泰兰徳羽月"] = {
				["name"] = "泰兰徳羽月",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["Usotall"] = {
				["name"] = "Usotall",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["小包子"] = {
				["name"] = "小包子",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["巨蟹座祭司"] = {
				["name"] = "巨蟹座祭司",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["缺大德了"] = {
				["name"] = "缺大德了",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["天蓝色的学"] = {
				["name"] = "天蓝色的学",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["福尔摩斯丶"] = {
				["name"] = "福尔摩斯丶",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["丨吉丨安娜"] = {
				["name"] = "丨吉丨安娜",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["葫芦仙"] = {
				["name"] = "葫芦仙",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
			["如月舞"] = {
				["name"] = "如月舞",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["雨爷"] = {
				["name"] = "雨爷",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["圣经丶冰"] = {
				["name"] = "圣经丶冰",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["祖鲁希德阿猫"] = {
				["name"] = "祖鲁希德阿猫",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["可爱的狸狸"] = {
				["name"] = "可爱的狸狸",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["约翰德蒙斯"] = {
				["name"] = "约翰德蒙斯",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 21:20:28",
		["reason"] = "国王议会",
		["foritem"] = "false",
		["points"] = 2,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["国王黑水愤怒下跪 2025-11-17 23:49:50"] = {
		["awarded"] = {
			["天蓝色的学"] = {
				["guild"] = "Unknown",
				["class"] = "战士",
				["name"] = "天蓝色的学",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "国王黑水愤怒下跪",
		["foritem"] = "false",
		["points"] = -1,
		["date"] = "2025-11-17 23:49:50",
		["tableid"] = 1,
	},
	["永恒之塔圣契 2025-11-17 20:57:10"] = {
		["awarded"] = {
			["Aviere"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "Aviere",
			},
		},
		["zone"] = "卡拉赞之塔",
		["awardedby"] = "安娜希尔",
		["reason"] = "永恒之塔圣契",
		["foritem"] = "false",
		["points"] = -6,
		["date"] = "2025-11-17 20:57:10",
		["tableid"] = 1,
	},
	["麦迪文 2025-11-17 20:56:37"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
			["三元奶"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "三元奶",
			},
			["坏小猪哥哥"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "坏小猪哥哥",
			},
			["莉莉丝丨"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "莉莉丝丨",
			},
			["石菖蒲"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "石菖蒲",
			},
			["神神气气"] = {
				["guild"] = "MirAcLe",
				["class"] = "盗贼",
				["name"] = "神神气气",
			},
			["程灵素"] = {
				["guild"] = "爱游戏爱生活",
				["class"] = "牧师",
				["name"] = "程灵素",
			},
			["天蓝色的学"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "天蓝色的学",
			},
			["锦果果"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "锦果果",
			},
			["我大戈六六"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "我大戈六六",
			},
			["Aviere"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "Aviere",
			},
			["还得我来"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "还得我来",
			},
			["Alexistina"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "Alexistina",
			},
			["大辣条"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "大辣条",
			},
			["皮皮丶"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "皮皮丶",
			},
			["淬锋"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "淬锋",
			},
			["安娜希尔"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "安娜希尔",
			},
			["郁眠"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "郁眠",
			},
			["血影寂灭"] = {
				["guild"] = "MirAcLe",
				["class"] = "盗贼",
				["name"] = "血影寂灭",
			},
			["柠檬酸了心"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "柠檬酸了心",
			},
			["老牛爹爹"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "老牛爹爹",
			},
			["嘎哈"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "嘎哈",
			},
			["大人是爱我的"] = {
				["guild"] = "橘猫在桂花树下而这里是我的平行世界",
				["class"] = "战士",
				["name"] = "大人是爱我的",
			},
			["此情念念不忘"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "此情念念不忘",
			},
			["有肉肉"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "有肉肉",
			},
			["泰兰徳羽月"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "泰兰徳羽月",
			},
			["Usotall"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "Usotall",
			},
			["小包子"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "小包子",
			},
			["巨蟹座祭司"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "巨蟹座祭司",
			},
			["缺大德了"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "缺大德了",
			},
			["可爱的狸狸"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
			["葫芦仙"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "葫芦仙",
			},
			["丨吉丨安娜"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "丨吉丨安娜",
			},
			["福尔摩斯丶"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "福尔摩斯丶",
			},
			["如月舞"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "如月舞",
			},
			["雨爷"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "雨爷",
			},
			["圣经丶冰"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "圣经丶冰",
			},
			["祖鲁希德阿猫"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "祖鲁希德阿猫",
			},
			["小黑手佳乐"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "小黑手佳乐",
			},
			["约翰德蒙斯"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "约翰德蒙斯",
			},
		},
		["zone"] = "卡拉赞之塔",
		["awardedby"] = "安娜希尔",
		["reason"] = "麦迪文",
		["foritem"] = "false",
		["points"] = 1,
		["date"] = "2025-11-17 20:56:37",
		["tableid"] = 1,
	},
	["镣铐 2025-11-17 23:22:58"] = {
		["awarded"] = {
			["三元奶"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "三元奶",
			},
			["锦果果"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "锦果果",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "镣铐",
		["foritem"] = "false",
		["points"] = -5,
		["date"] = "2025-11-17 23:22:58",
		["tableid"] = 1,
	},
	["库鲁尔 2025-11-17 22:33:48"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
			["三元奶"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "三元奶",
			},
			["坏小猪哥哥"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "坏小猪哥哥",
			},
			["莉莉丝丨"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "莉莉丝丨",
			},
			["神神气气"] = {
				["guild"] = "MirAcLe",
				["class"] = "盗贼",
				["name"] = "神神气气",
			},
			["程灵素"] = {
				["guild"] = "爱游戏爱生活",
				["class"] = "牧师",
				["name"] = "程灵素",
			},
			["天蓝色的学"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "天蓝色的学",
			},
			["锦果果"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "锦果果",
			},
			["我大戈六六"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "我大戈六六",
			},
			["Aviere"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "Aviere",
			},
			["还得我来"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "还得我来",
			},
			["Alexistina"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "Alexistina",
			},
			["大辣条"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "大辣条",
			},
			["皮皮丶"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "皮皮丶",
			},
			["淬锋"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "淬锋",
			},
			["安娜希尔"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "安娜希尔",
			},
			["郁眠"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "郁眠",
			},
			["血影寂灭"] = {
				["guild"] = "MirAcLe",
				["class"] = "盗贼",
				["name"] = "血影寂灭",
			},
			["柠檬酸了心"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "柠檬酸了心",
			},
			["老牛爹爹"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "老牛爹爹",
			},
			["嘎哈"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "嘎哈",
			},
			["大人是爱我的"] = {
				["guild"] = "橘猫在桂花树下而这里是我的平行世界",
				["class"] = "战士",
				["name"] = "大人是爱我的",
			},
			["此情念念不忘"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "此情念念不忘",
			},
			["可爱的狸狸"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
			["泰兰徳羽月"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "泰兰徳羽月",
			},
			["Usotall"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "Usotall",
			},
			["小包子"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "小包子",
			},
			["巨蟹座祭司"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "巨蟹座祭司",
			},
			["缺大德了"] = {
				["guild"] = "MirAcLe",
				["class"] = "德鲁伊",
				["name"] = "缺大德了",
			},
			["小黑手佳乐"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "小黑手佳乐",
			},
			["雨爷"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "雨爷",
			},
			["丨吉丨安娜"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "丨吉丨安娜",
			},
			["葫芦仙"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "葫芦仙",
			},
			["如月舞"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "如月舞",
			},
			["阿牛"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "阿牛",
			},
			["圣经丶冰"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "圣经丶冰",
			},
			["祖鲁希德阿猫"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "祖鲁希德阿猫",
			},
			["有肉肉"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "有肉肉",
			},
			["约翰德蒙斯"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "约翰德蒙斯",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "库鲁尔",
		["foritem"] = "false",
		["points"] = 1,
		["date"] = "2025-11-17 22:33:48",
		["tableid"] = 1,
	},
	["破碎征服之冠 2025-11-17 22:11:43"] = {
		["awarded"] = {
			["三元奶"] = {
				["class"] = "牧师",
				["name"] = "三元奶",
			},
			["可爱的狸狸"] = {
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "破碎征服之冠",
		["foritem"] = "false",
		["points"] = -31,
		["date"] = "2025-11-17 22:11:43",
		["tableid"] = 1,
	},
	["被遗忘的黎明斗篷 2025-11-17 21:23:17"] = {
		["awarded"] = {
			["安娜希尔"] = {
				["name"] = "安娜希尔",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 21:23:17",
		["reason"] = "被遗忘的黎明斗篷",
		["foritem"] = "false",
		["points"] = -10,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["扣错补回5分 2025-11-17 22:12:04"] = {
		["awarded"] = {
			["三元奶"] = {
				["class"] = "牧师",
				["name"] = "三元奶",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "扣错补回5分",
		["foritem"] = "false",
		["points"] = 5,
		["date"] = "2025-11-17 22:12:04",
		["tableid"] = 1,
	},
	["压制能量遗物 2025-11-17 20:38:56"] = {
		["awarded"] = {
			["祖鲁希德阿猫"] = {
				["name"] = "祖鲁希德阿猫",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 20:38:56",
		["reason"] = "压制能量遗物",
		["foritem"] = "false",
		["points"] = -21,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["阿诺玛鲁斯 2025-11-17 20:38:02"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["name"] = "认养一头母牛",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["三元奶"] = {
				["name"] = "三元奶",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
			["坏小猪哥哥"] = {
				["name"] = "坏小猪哥哥",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["莉莉丝丨"] = {
				["name"] = "莉莉丝丨",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["石菖蒲"] = {
				["name"] = "石菖蒲",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["神神气气"] = {
				["name"] = "神神气气",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["程灵素"] = {
				["name"] = "程灵素",
				["class"] = "牧师",
				["guild"] = "爱游戏爱生活",
			},
			["小黑手佳乐"] = {
				["name"] = "小黑手佳乐",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["锦果果"] = {
				["name"] = "锦果果",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["我大戈六六"] = {
				["name"] = "我大戈六六",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["Aviere"] = {
				["name"] = "Aviere",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["还得我来"] = {
				["name"] = "还得我来",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["Alexistina"] = {
				["name"] = "Alexistina",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["大辣条"] = {
				["name"] = "大辣条",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["皮皮丶"] = {
				["name"] = "皮皮丶",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["淬锋"] = {
				["name"] = "淬锋",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["安娜希尔"] = {
				["name"] = "安娜希尔",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["郁眠"] = {
				["name"] = "郁眠",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["血影寂灭"] = {
				["name"] = "血影寂灭",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["柠檬酸了心"] = {
				["name"] = "柠檬酸了心",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["老牛爹爹"] = {
				["name"] = "老牛爹爹",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["嘎哈"] = {
				["name"] = "嘎哈",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["大人是爱我的"] = {
				["name"] = "大人是爱我的",
				["class"] = "战士",
				["guild"] = "橘猫在桂花树下而这里是我的平行世界",
			},
			["此情念念不忘"] = {
				["name"] = "此情念念不忘",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["可爱的狸狸"] = {
				["name"] = "可爱的狸狸",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["泰兰徳羽月"] = {
				["name"] = "泰兰徳羽月",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["Usotall"] = {
				["name"] = "Usotall",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["小包子"] = {
				["name"] = "小包子",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["巨蟹座祭司"] = {
				["name"] = "巨蟹座祭司",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["缺大德了"] = {
				["name"] = "缺大德了",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["天蓝色的学"] = {
				["name"] = "天蓝色的学",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["福尔摩斯丶"] = {
				["name"] = "福尔摩斯丶",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["丨吉丨安娜"] = {
				["name"] = "丨吉丨安娜",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["葫芦仙"] = {
				["name"] = "葫芦仙",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
			["如月舞"] = {
				["name"] = "如月舞",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["雨爷"] = {
				["name"] = "雨爷",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["圣经丶冰"] = {
				["name"] = "圣经丶冰",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["祖鲁希德阿猫"] = {
				["name"] = "祖鲁希德阿猫",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["有肉肉"] = {
				["name"] = "有肉肉",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["约翰德蒙斯"] = {
				["name"] = "约翰德蒙斯",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 20:38:02",
		["reason"] = "阿诺玛鲁斯",
		["foritem"] = "false",
		["points"] = 1,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["魔法火花护腿 2025-11-17 20:06:44"] = {
		["awarded"] = {
			["老牛爹爹"] = {
				["guild"] = "MirAcLe",
				["class"] = "萨满祭司",
				["name"] = "老牛爹爹",
			},
		},
		["zone"] = "卡拉赞之塔",
		["awardedby"] = "安娜希尔",
		["reason"] = "魔法火花护腿",
		["foritem"] = "false",
		["points"] = -1,
		["date"] = "2025-11-17 20:06:44",
		["tableid"] = 1,
	},
	["失误 2025-11-17 19:43:52"] = {
		["awarded"] = {
			["血影寂灭"] = {
				["class"] = "盗贼",
				["name"] = "血影寂灭",
			},
		},
		["zone"] = "逆风小径",
		["date"] = "2025-11-17 19:43:52",
		["reason"] = "失误",
		["foritem"] = "false",
		["points"] = -1,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["短暂吊坠 2025-11-17 21:20:55"] = {
		["awarded"] = {
			["雨爷"] = {
				["name"] = "雨爷",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 21:20:55",
		["reason"] = "短暂吊坠",
		["foritem"] = "false",
		["points"] = -60,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["地狱业火 2025-11-17 22:36:46"] = {
		["awarded"] = {
			["祖鲁希德阿猫"] = {
				["guild"] = "MirAcLe",
				["class"] = "法师",
				["name"] = "祖鲁希德阿猫",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "地狱业火",
		["foritem"] = "false",
		["points"] = -3,
		["date"] = "2025-11-17 22:36:46",
		["tableid"] = 1,
	},
	["Version"] = 2,
	["桑夫 2025-11-17 21:46:40"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["name"] = "认养一头母牛",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["三元奶"] = {
				["name"] = "三元奶",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
			["坏小猪哥哥"] = {
				["name"] = "坏小猪哥哥",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["莉莉丝丨"] = {
				["name"] = "莉莉丝丨",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["石菖蒲"] = {
				["name"] = "石菖蒲",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["神神气气"] = {
				["name"] = "神神气气",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["程灵素"] = {
				["name"] = "程灵素",
				["class"] = "牧师",
				["guild"] = "爱游戏爱生活",
			},
			["小黑手佳乐"] = {
				["name"] = "小黑手佳乐",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["锦果果"] = {
				["name"] = "锦果果",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["我大戈六六"] = {
				["name"] = "我大戈六六",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["Aviere"] = {
				["name"] = "Aviere",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["还得我来"] = {
				["name"] = "还得我来",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["Alexistina"] = {
				["name"] = "Alexistina",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["大辣条"] = {
				["name"] = "大辣条",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["皮皮丶"] = {
				["name"] = "皮皮丶",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["淬锋"] = {
				["name"] = "淬锋",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["安娜希尔"] = {
				["name"] = "安娜希尔",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["郁眠"] = {
				["name"] = "郁眠",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["血影寂灭"] = {
				["name"] = "血影寂灭",
				["class"] = "盗贼",
				["guild"] = "MirAcLe",
			},
			["柠檬酸了心"] = {
				["name"] = "柠檬酸了心",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["老牛爹爹"] = {
				["name"] = "老牛爹爹",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["嘎哈"] = {
				["name"] = "嘎哈",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["大人是爱我的"] = {
				["name"] = "大人是爱我的",
				["class"] = "战士",
				["guild"] = "橘猫在桂花树下而这里是我的平行世界",
			},
			["此情念念不忘"] = {
				["name"] = "此情念念不忘",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["有肉肉"] = {
				["name"] = "有肉肉",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["泰兰徳羽月"] = {
				["name"] = "泰兰徳羽月",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["Usotall"] = {
				["name"] = "Usotall",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["小包子"] = {
				["name"] = "小包子",
				["class"] = "术士",
				["guild"] = "MirAcLe",
			},
			["缺大德了"] = {
				["name"] = "缺大德了",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["巨蟹座祭司"] = {
				["name"] = "巨蟹座祭司",
				["class"] = "萨满祭司",
				["guild"] = "MirAcLe",
			},
			["天蓝色的学"] = {
				["name"] = "天蓝色的学",
				["class"] = "战士",
				["guild"] = "MirAcLe",
			},
			["丨吉丨安娜"] = {
				["name"] = "丨吉丨安娜",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["葫芦仙"] = {
				["name"] = "葫芦仙",
				["class"] = "牧师",
				["guild"] = "MirAcLe",
			},
			["如月舞"] = {
				["name"] = "如月舞",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["雨爷"] = {
				["name"] = "雨爷",
				["class"] = "猎人",
				["guild"] = "MirAcLe",
			},
			["圣经丶冰"] = {
				["name"] = "圣经丶冰",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
			["祖鲁希德阿猫"] = {
				["name"] = "祖鲁希德阿猫",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
			["可爱的狸狸"] = {
				["name"] = "可爱的狸狸",
				["class"] = "德鲁伊",
				["guild"] = "MirAcLe",
			},
			["约翰德蒙斯"] = {
				["name"] = "约翰德蒙斯",
				["class"] = "圣骑士",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "荒芜巨岩",
		["date"] = "2025-11-17 21:46:40",
		["reason"] = "桑夫",
		["foritem"] = "false",
		["points"] = 1,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["野蛮征服护腿 2025-11-17 22:36:23"] = {
		["awarded"] = {
			["小包子"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "小包子",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "野蛮征服护腿",
		["foritem"] = "false",
		["points"] = -36,
		["date"] = "2025-11-17 22:36:23",
		["tableid"] = 1,
	},
	["湿透的羽毛便鞋 2025-11-17 19:55:22"] = {
		["awarded"] = {
			["祖鲁希德阿猫"] = {
				["name"] = "祖鲁希德阿猫",
				["class"] = "法师",
				["guild"] = "MirAcLe",
			},
		},
		["zone"] = "卡拉赞之塔",
		["date"] = "2025-11-17 19:55:22",
		["reason"] = "湿透的羽毛便鞋",
		["foritem"] = "false",
		["points"] = -1,
		["awardedby"] = "安娜希尔",
		["tableid"] = 1,
	},
	["解散 2025-11-17 23:35:01"] = {
		["awarded"] = {
			["认养一头母牛"] = {
				["class"] = "萨满祭司",
				["name"] = "认养一头母牛",
			},
			["三元奶"] = {
				["class"] = "牧师",
				["name"] = "三元奶",
			},
			["坏小猪哥哥"] = {
				["class"] = "战士",
				["name"] = "坏小猪哥哥",
			},
			["莉莉丝丨"] = {
				["class"] = "德鲁伊",
				["name"] = "莉莉丝丨",
			},
			["神神气气"] = {
				["class"] = "盗贼",
				["name"] = "神神气气",
			},
			["程灵素"] = {
				["class"] = "牧师",
				["name"] = "程灵素",
			},
			["天蓝色的学"] = {
				["class"] = "战士",
				["name"] = "天蓝色的学",
			},
			["锦果果"] = {
				["guild"] = "MirAcLe",
				["class"] = "战士",
				["name"] = "锦果果",
			},
			["我大戈六六"] = {
				["class"] = "战士",
				["name"] = "我大戈六六",
			},
			["Aviere"] = {
				["class"] = "圣骑士",
				["name"] = "Aviere",
			},
			["还得我来"] = {
				["class"] = "法师",
				["name"] = "还得我来",
			},
			["Alexistina"] = {
				["class"] = "战士",
				["name"] = "Alexistina",
			},
			["一君莫笑一"] = {
				["class"] = "法师",
				["name"] = "一君莫笑一",
			},
			["皮皮丶"] = {
				["class"] = "法师",
				["name"] = "皮皮丶",
			},
			["淬锋"] = {
				["class"] = "战士",
				["name"] = "淬锋",
			},
			["安娜希尔"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "安娜希尔",
			},
			["郁眠"] = {
				["class"] = "圣骑士",
				["name"] = "郁眠",
			},
			["血影寂灭"] = {
				["class"] = "盗贼",
				["name"] = "血影寂灭",
			},
			["柠檬酸了心"] = {
				["class"] = "法师",
				["name"] = "柠檬酸了心",
			},
			["老牛爹爹"] = {
				["class"] = "萨满祭司",
				["name"] = "老牛爹爹",
			},
			["嘎哈"] = {
				["class"] = "萨满祭司",
				["name"] = "嘎哈",
			},
			["大人是爱我的"] = {
				["class"] = "战士",
				["name"] = "大人是爱我的",
			},
			["此情念念不忘"] = {
				["class"] = "术士",
				["name"] = "此情念念不忘",
			},
			["一染尽红尘"] = {
				["class"] = "战士",
				["name"] = "一染尽红尘",
			},
			["泰兰徳羽月"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "泰兰徳羽月",
			},
			["Usotall"] = {
				["class"] = "萨满祭司",
				["name"] = "Usotall",
			},
			["小包子"] = {
				["guild"] = "MirAcLe",
				["class"] = "术士",
				["name"] = "小包子",
			},
			["大辣条"] = {
				["class"] = "德鲁伊",
				["name"] = "大辣条",
			},
			["巨蟹座祭司"] = {
				["class"] = "萨满祭司",
				["name"] = "巨蟹座祭司",
			},
			["缺大德了"] = {
				["class"] = "德鲁伊",
				["name"] = "缺大德了",
			},
			["可爱的狸狸"] = {
				["class"] = "德鲁伊",
				["name"] = "可爱的狸狸",
			},
			["如月舞"] = {
				["class"] = "圣骑士",
				["name"] = "如月舞",
			},
			["丨吉丨安娜"] = {
				["class"] = "法师",
				["name"] = "丨吉丨安娜",
			},
			["葫芦仙"] = {
				["guild"] = "MirAcLe",
				["class"] = "牧师",
				["name"] = "葫芦仙",
			},
			["小黑手佳乐"] = {
				["class"] = "战士",
				["name"] = "小黑手佳乐",
			},
			["雨爷"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "雨爷",
			},
			["圣经丶冰"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "圣经丶冰",
			},
			["祖鲁希德阿猫"] = {
				["class"] = "法师",
				["name"] = "祖鲁希德阿猫",
			},
			["有肉肉"] = {
				["class"] = "猎人",
				["name"] = "有肉肉",
			},
			["约翰德蒙斯"] = {
				["guild"] = "MirAcLe",
				["class"] = "圣骑士",
				["name"] = "约翰德蒙斯",
			},
		},
		["zone"] = "荒芜巨岩",
		["awardedby"] = "安娜希尔",
		["reason"] = "解散",
		["foritem"] = "false",
		["points"] = 2,
		["date"] = "2025-11-17 23:35:01",
		["tableid"] = 1,
	},
	["镣铐 2025-11-17 22:47:29"] = {
		["awarded"] = {
			["有肉肉"] = {
				["guild"] = "MirAcLe",
				["class"] = "猎人",
				["name"] = "有肉肉",
			},
			["程灵素"] = {
				["guild"] = "爱游戏爱生活",
				["class"] = "牧师",
				["name"] = "程灵素",
			},
		},
		["zone"] = "逆风小径",
		["awardedby"] = "安娜希尔",
		["reason"] = "镣铐",
		["foritem"] = "false",
		["points"] = -2,
		["date"] = "2025-11-17 22:47:29",
		["tableid"] = 1,
	},
}
WebDKP_DkpTable = {
	["Jyy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["襄儿"] = {
		["dkp1"] = 0,
		["dkp_1"] = 33.47,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["阿迩忒弥絲丝"] = {
		["dkp1"] = 0,
		["dkp_1"] = 41.42,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["江流自然之力"] = {
		["dkp1"] = 0,
		["dkp_1"] = 8.5,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["Nicedayy"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["锦果果"] = {
		["dkp1"] = 0,
		["dkp_1"] = 40.7,
		["Selected"] = false,
		["class"] = "战士",
	},
	["绊你一跟头"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["叶落丶翼德"] = {
		["dkp1"] = 0,
		["dkp_1"] = 26.7,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["石菖蒲"] = {
		["dkp1"] = 0,
		["dkp_1"] = 2,
		["Selected"] = false,
		["class"] = "法师",
	},
	["皮皮丶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 43.38,
		["Selected"] = false,
		["class"] = "法师",
	},
	["淬锋"] = {
		["dkp1"] = 0,
		["dkp_1"] = 39.49,
		["Selected"] = false,
		["class"] = "战士",
	},
	["冰猫"] = {
		["dkp1"] = 0,
		["dkp_1"] = 29.13,
		["Selected"] = false,
		["class"] = "战士",
	},
	["森间魅影"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["Peepsi"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["大人是爱我的"] = {
		["dkp1"] = 0,
		["dkp_1"] = 34.17,
		["Selected"] = false,
		["class"] = "战士",
	},
	["有肉肉"] = {
		["dkp1"] = 0,
		["dkp_1"] = 37.39,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["泰兰徳羽月"] = {
		["dkp1"] = 0,
		["dkp_1"] = 29.21,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["Usotall"] = {
		["dkp1"] = 0,
		["dkp_1"] = 46.94,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["豚鼠少校"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["小虎妈妈"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "术士",
	},
	["缺大德了"] = {
		["dkp1"] = 0,
		["dkp_1"] = 21.72,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["丨吉丨安娜"] = {
		["dkp1"] = 0,
		["dkp_1"] = 17.3,
		["Selected"] = false,
		["class"] = "法师",
	},
	["葫芦仙"] = {
		["dkp1"] = 0,
		["dkp_1"] = 16.81,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["泰兰德羽月"] = {
		["dkp1"] = 0,
		["dkp_1"] = 42.21,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["圣经丶冰"] = {
		["dkp1"] = 0,
		["dkp_1"] = 12.71,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["Mayandc"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["认养一头母牛"] = {
		["dkp1"] = 0,
		["dkp_1"] = 21.31,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["三元奶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 14.63,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["红叶碎月焚霜"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["灾厄林克"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["灬乌龙茶灬"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "战士",
	},
	["坏小猪哥哥"] = {
		["dkp1"] = 0,
		["dkp_1"] = 56.44,
		["Selected"] = false,
		["class"] = "战士",
	},
	["莉莉丝丨"] = {
		["dkp1"] = 0,
		["dkp_1"] = 33.12000000000001,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["石菖蒲"] = {
		["dkp1"] = 0,
		["dkp_1"] = 9.859999999999999,
		["Selected"] = false,
		["class"] = "术士",
	},
	["神神气气"] = {
		["dkp1"] = 0,
		["dkp_1"] = 30.79,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["程灵素"] = {
		["dkp1"] = 0,
		["dkp_1"] = 29.46,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["天蓝色的学"] = {
		["dkp1"] = 0,
		["dkp_1"] = 29.7,
		["Selected"] = false,
		["class"] = "战士",
	},
	["风二郎"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["我大戈六六"] = {
		["dkp1"] = 0,
		["dkp_1"] = 53.99,
		["Selected"] = false,
		["class"] = "战士",
	},
	["Aviere"] = {
		["dkp1"] = 0,
		["dkp_1"] = 16.91,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["翡翠村的男神"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["还得我来"] = {
		["dkp1"] = 0,
		["dkp_1"] = 17.75,
		["Selected"] = false,
		["class"] = "法师",
	},
	["大辣条"] = {
		["dkp1"] = 0,
		["dkp_1"] = 31.5,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["巨蟹座祭司"] = {
		["dkp1"] = 0,
		["dkp_1"] = 18.75,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["安娜希尔"] = {
		["dkp1"] = 0,
		["dkp_1"] = 31.03,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["郁眠"] = {
		["dkp1"] = 0,
		["dkp_1"] = 17.34,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["血影寂灭"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10.21,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["柠檬酸了心"] = {
		["dkp1"] = 0,
		["dkp_1"] = 45.04,
		["Selected"] = false,
		["class"] = "法师",
	},
	["老牛爹爹"] = {
		["dkp1"] = 0,
		["dkp_1"] = 32.84,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["嘎哈"] = {
		["dkp1"] = 0,
		["dkp_1"] = 37.87000000000001,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["此情念念不忘"] = {
		["dkp1"] = 0,
		["dkp_1"] = 25.21,
		["Selected"] = false,
		["class"] = "术士",
	},
	["可爱的狸狸"] = {
		["dkp1"] = 0,
		["dkp_1"] = 9.34,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["贼酷之名"] = {
		["dkp1"] = 0,
		["dkp_1"] = 17.6,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["缺大德儿"] = {
		["dkp1"] = 0,
		["dkp_1"] = 23.72,
		["Selected"] = false,
		["class"] = "德鲁伊",
	},
	["Alexistina"] = {
		["dkp1"] = 0,
		["dkp_1"] = 64.56,
		["Selected"] = false,
		["class"] = "战士",
	},
	["小包子"] = {
		["dkp1"] = 0,
		["dkp_1"] = 7.049999999999997,
		["Selected"] = false,
		["class"] = "术士",
	},
	["祖德希德阿猫"] = {
		["dkp1"] = 0,
		["dkp_1"] = 22.03,
		["Selected"] = false,
		["class"] = "法师",
	},
	["麻豆男主角"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["封心贼"] = {
		["dkp1"] = 0,
		["dkp_1"] = 12.75,
		["Selected"] = false,
		["class"] = "盗贼",
	},
	["波兰小诗"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["甜心奶兔酱"] = {
		["dkp1"] = 0,
		["dkp_1"] = 27.3,
		["Selected"] = false,
		["class"] = "萨满祭司",
	},
	["小黑手佳乐"] = {
		["dkp1"] = 0,
		["dkp_1"] = 20.65,
		["Selected"] = false,
		["class"] = "战士",
	},
	["雨爷"] = {
		["dkp1"] = 0,
		["dkp_1"] = 19.01000000000001,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["如月舞"] = {
		["dkp1"] = 0,
		["dkp_1"] = 47.07,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
	["林若雲"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "猎人",
	},
	["霜华"] = {
		["dkp1"] = 0,
		["dkp_1"] = 11.56,
		["Selected"] = false,
		["class"] = "牧师",
	},
	["福尔摩斯丶"] = {
		["dkp1"] = 0,
		["dkp_1"] = 45.17,
		["Selected"] = false,
		["class"] = "术士",
	},
	["未知目标"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
	},
	["阿牛"] = {
		["dkp1"] = 0,
		["dkp_1"] = 39.68,
		["Selected"] = false,
		["class"] = "战士",
	},
	["一染尽红尘"] = {
		["dkp1"] = 0,
		["dkp_1"] = 7.33,
		["Selected"] = false,
		["class"] = "战士",
	},
	["祖鲁希德阿猫"] = {
		["dkp1"] = 0,
		["dkp_1"] = 10.03,
		["Selected"] = false,
		["class"] = "法师",
	},
	["蜜蜜是玳瑁"] = {
		["dkp1"] = 0,
		["dkp_1"] = 0,
		["Selected"] = false,
		["class"] = "法师",
	},
	["约翰德蒙斯"] = {
		["dkp1"] = 0,
		["dkp_1"] = 20.93,
		["Selected"] = false,
		["class"] = "圣骑士",
	},
}
WebDKP_Tables = {
}
WebDKP_Loot = nil
WebDKP_WebOptions = {
	["ZeroSumEnabled"] = 0,
}
